# -*- coding: utf-8 -*-
"""
Wrapper agar file notebook-style (.ipynb) bisa dijalankan sebagai .py
tanpa error SyntaxError pada baris yang mengandung tanda '!'
"""

import sys, subprocess, tempfile, textwrap

# ====== Masukkan script asli di bawah ini dalam bentuk string ======
script = textwrap.dedent(r'''
# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DVjxHkFYYEbKiapwcu1S9yHxfURM753p
"""

# =====================================================
# === 1. Install library ===
# =====================================================
!pip install xarray netCDF4 numpy matplotlib cartopy

import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

# =====================================================
# === 2. Buka file wrfout ===
# =====================================================
ncfile = '/content/wrfout_d03_2024-03-12_00:00:00'
ds = xr.open_dataset(ncfile)

# =====================================================
# === 3. Ambil variabel curah hujan ===
# =====================================================
rainc = ds['RAINC']
rainnc = ds['RAINNC']
rain_total = rainc + rainnc

# =====================================================
# === 4. Hitung rain rate (mm/jam) ===
# =====================================================
rain_diff = rain_total.diff(dim='Time')
time_diff = (rain_total['Time'].diff(dim='Time') / np.timedelta64(1, 'h')).astype(float)
time_diff_3d = time_diff[:, None, None]
rain_rate = rain_diff / time_diff_3d
rain_rate.name = 'rain_rate'
rain_rate.attrs['units'] = 'mm/h'

# =====================================================
# === 5. Plot peta rain rate ===
# =====================================================
lat = ds['XLAT'].isel(Time=0)
lon = ds['XLONG'].isel(Time=0)
rain_plot = rain_rate.isel(Time=-1)

plt.figure(figsize=(8,6))
ax = plt.axes(projection=ccrs.PlateCarree())
ax.coastlines()
plt.title("Rain Rate (mm/jam)")
p = plt.pcolormesh(lon, lat, rain_plot, cmap='Blues', transform=ccrs.PlateCarree())
plt.colorbar(p, ax=ax, label='mm/jam')
plt.show()

# =====================================================
# === 6. Simpan hasil rain rate ke NetCDF baru ===
# =====================================================
rain_rate.to_netcdf('/content/rain_rate_wrf.nc')
print("✅ Rain rate disimpan sebagai rain_rate_wrf.nc")
''')

# ====== Eksekusi script asli dengan interpreter "notebook-safe" ======
# Ubah baris dengan "!" menjadi perintah pip lewat subprocess
safe_script = "\n".join(
    line if not line.strip().startswith("!") 
    else f"subprocess.check_call({[sys.executable, '-m', 'pip'] + line.strip('!').split()})"
    for line in script.splitlines()
)

# Jalankan script hasil konversi
exec(safe_script, globals())
