# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DVjxHkFYYEbKiapwcu1S9yHxfURM753p
"""

# =====================================================
# === 1. Install library ===
# =====================================================
import sys, subprocess

# Deteksi apakah dijalankan di luar Google Colab
if "google.colab" not in sys.modules:
    subprocess.check_call([sys.executable, "-m", "pip", "install", 
                           "xarray", "netCDF4", "numpy", "matplotlib", "cartopy"])
else:
    # Hanya berjalan di Google Colab
    !pip install xarray netCDF4 numpy matplotlib cartopy

# =====================================================
# === 2. Import library ===
# =====================================================
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

# =====================================================
# === 3. Buka file wrfout ===
# =====================================================
# Upload file NetCDF (misal: wrfout_d01_2024-03-12_00:00:00)
# atau sesuaikan path di bawah:
ncfile = '/content/wrfout_d03_2024-03-12_00:00:00'

# Buka file dengan xarray
ds = xr.open_dataset(ncfile)

# =====================================================
# === 4. Ambil variabel curah hujan ===
# =====================================================
rainc = ds['RAINC']    # Convective rain (mm)
rainnc = ds['RAINNC']  # Non-convective rain (mm)
rain_total = rainc + rainnc

# =====================================================
# === 5. Hitung rain rate (mm/jam) ===
# =====================================================
# Ambil selisih antar waktu (mm)
rain_diff = rain_total.diff(dim='Time')

# Hitung interval waktu dalam jam and convert to float
time_diff = (rain_total['Time'].diff(dim='Time') / np.timedelta64(1, 'h')).astype(float)

# Broadcast agar sesuai dimensi
time_diff_3d = time_diff[:, None, None]

# Rain rate = Δrain / Δt
rain_rate = rain_diff / time_diff_3d
rain_rate.name = 'rain_rate'
rain_rate.attrs['units'] = 'mm/h'

# =====================================================
# === 6. Plot peta rain rate ===
# =====================================================
# Ambil data lat/lon
lat = ds['XLAT'].isel(Time=0)
lon = ds['XLONG'].isel(Time=0)

# Pilih waktu terakhir untuk contoh visualisasi
rain_plot = rain_rate.isel(Time=-1)

plt.figure(figsize=(8,6))
ax = plt.axes(projection=ccrs.PlateCarree())
ax.coastlines()
plt.title("Rain Rate (mm/jam)")
p = plt.pcolormesh(lon, lat, rain_plot, cmap='Blues', transform=ccrs.PlateCarree())
plt.colorbar(p, ax=ax, label='mm/jam')
plt.show()

# =====================================================
# === 7. Simpan hasil rain rate ke NetCDF baru ===
# =====================================================
rain_rate.to_netcdf('/content/rain_rate_wrf.nc')
print("✅ Rain rate disimpan sebagai rain_rate_wrf.nc")
